framework: convlstm
network: 
    lstm_units: 512
    load_lstm: checkpoints/seq_next_diff/3.model
optimizer:
    type: SGD
    lr: 0.0003
    momentum: 0.9
    weight_decay: 0.001
data:
    length: 16
    loop: 2
