framework: convlstm
network: 
    lstm_units: 512
    load_lstm: checkpoints/seqorder_fix_moment_lr0.01/3.model
    load_backbone: checkpoints/seqorder_fix_moment_lr0.01/3.model
optimizer:
    type: SGD
    lr: 0.001
    weight_decay: 0.001
data:
    length: 16
    loop: 2
