framework: convlstm
network: 
    lstm_units: 512
    load_lstm: checkpoints/seqorder_moment_lr0.01/2.model
    load_backbone: checkpoints/seqorder_moment_lr0.01/2.model
optimizer:
    type: SGD
    lr: 0.001
    weight_decay: 0.0001
data:
    length: 16
    loop: 2
