framework: convlstm
network: 
    lstm_units: 512
    load_lstm: checkpoints/seqorder/2.model
    load_backbone: checkpoints/seqorder/2.model
optimizer:
    type: Adam
    weight_decay: 0.001
data:
    length: 16
    loop: 2
