framework: seqpred
network: 
    lstm_units: 512
    task: order-frame
    train_backbone: True
optimizer:
    type: Adam
    weight_decay: 0.0001
data:
    version: v1
    length: 2 
    loop: 4
    feature: False
