framework: seq
network: 
    lstm_units: 1024
    train_backbone: False
optimizer:
    type: Adam
    lr: 0.001
    weight_decay: 0.0001
data:
    version: v2
    length: 17
    loop: 1
    feature: False
