framework: seqpred
network: 
    lstm_units: 512
    task: order
    train_backbone: True
optimizer:
    type: Adam
    weight_decay: 0.0001
data:
    version: v1
    length: 18 
    loop: 1
    feature: False
